### ISSUE TITLE
Storing long int variable

### ISSUE THREAD

**Issue by jning8401** [kgabis/parson#113] opened 2019-02-20 19:56 UTC
When passing long int variables to json_object_dotset_number() API, the output looks like:

    "memoryUsage": {
        "freeMemory (bytes)": 99545470608.000000,
        "usedMemory (bytes)": 20545570160.000000,
        "totalMemory (bytes)": 120091040768.000000
    }

Is there anyway to remove the decimals? I know that json_object_dotset_number() converts the input to double. Input as integer does not have have decimals in the output. Thanks a lot!

**Comment by kgabis** [comment] 2019-02-20 20:08
I'm unable to reproduce your results.

```c
    JSON_Value *root_value = json_value_init_object();
    JSON_Object *root_object = json_value_get_object(root_value);

    json_object_dotset_number(root_object, "freeMemory (bytes)", 99545470608);
    json_object_dotset_number(root_object, "usedMemory (bytes)", 20545570160);
    json_object_dotset_number(root_object, "totalMemory (bytes)", 120091040768);

    puts(json_serialize_to_string_pretty(root_value));
```
prints
```json
{
    "freeMemory (bytes)": 99545470608,
    "usedMemory (bytes)": 20545570160,
    "totalMemory (bytes)": 120091040768
}
```

**Comment by kgabis** [comment] 2019-02-24 10:53
I'm closing this issue because I suspect you were using an old version of parson.

**Closed by kgabis** 2019-02-24 10:53 UTC

**Comment by jning8401** [comment] 2019-03-04 19:59
Using the most recent version resolves the issue. thanks!
