### ISSUE TITLE
Found a bug!

### ISSUE THREAD

**Issue by shu7734** [kgabis/parson#154] opened 2021-02-23 07:16 UTC
STREQ(json_object_get_string(root_object, "utf string"), "lorem ipsum中华人2民共和国")- FAIL
STREQ(json_object_get_string(root_object, "utf-8 string"), "中国あいうえお")- FAIL

**Comment by kgabis** [comment] 2021-02-23 09:59
Did you just change code in tests.c without changing files used for those tests?
Please provide a way of reproducing this "bug'.

**Comment by shu7734** [comment] 2021-02-23 10:01
I just changed test.c

    TEST(json_object_set_string(obj, "utf string", "lorem ipsum中华人2民共和国") == JSONSuccess);
    TEST(json_object_set_string(obj, "utf-8 string", "あい中国うえお") == JSONSuccess);

**Comment by kgabis** [comment] 2021-02-23 10:04
You need to change ```tests/test_2.txt``` and ```tests/test_2_comments.txt``` as well.

**Comment by shu7734** [comment] 2021-02-23 10:12
Thank You

Is Work now！
But json_object_set_string not work in VS2019 when  used "中华人民共和国" or any chinese word。
code:

JSON_Value *root_value = json_value_init_object();
    JSON_Object *root_object = json_value_get_object(root_value);
    char *serialized_string = NULL;
    json_object_set_string(root_object, "name", "中华人民共和国");
    json_object_set_number(root_object, "age", 25);
serialized_string = json_serialize_to_string(root_value);
printf(serialized_string);
    json_free_serialized_string(serialized_string);
    json_value_free(root_value);

**Comment by kgabis** [comment] 2021-02-23 10:14
Is your source file encoded using utf8?

**Comment by shu7734** [comment] 2021-02-23 10:15
is Worked from cJson+VS2019

	char* name = "中华人2民共和国";
	cJSON* objjson = cJSON_CreateObject();
	cJSON_AddNumberToObject(objjson, "code", 120);
	cJSON_AddStringToObject(objjson, "data", name);
	char* serialized_string = cJSON_Print(objjson);

	printf(serialized_string);

**Comment by shu7734** [comment] 2021-02-23 10:16
No,encoded used gb2312

**Comment by shu7734** [comment] 2021-02-23 10:16
cpp file encoded gb2312

**Comment by kgabis** [comment] 2021-02-23 10:17
Please change it to utf-8, it should help.

**Comment by shu7734** [comment] 2021-02-23 10:18
Thank You! I'll give it a try

**Comment by shu7734** [comment] 2021-02-23 10:20
if I receved chinese word from network，I need change to UTF-8？

**Comment by shu7734** [comment] 2021-02-23 10:20
if I receved chinese word from network，I need change to UTF-8？

**Comment by kgabis** [comment] 2021-02-23 11:11
gb2312 is a subset of unicode so it should work.

Does your example work after changing
```json_object_set_string(root_object, "name", "中华人民共和国");``` 
to
```json_object_set_string(root_object, "name", u8"中华人民共和国");```
?

**Comment by kgabis** [comment] 2021-02-24 11:13
I'm closing this issue since it seems to be a problem in your setup.

**Closed by kgabis** 2021-02-24 11:13 UTC
