### ISSUE TITLE
UTF-8 symbols

### ISSUE THREAD

**Issue by vasiliyph** [kgabis/parson#64] opened 2016-10-25 23:31 UTC
Can't process some UTF-8 symbols.
JSON example: http://pastebin.com/3ZzNPup5
Fail to serialize "\u0001" in end of file.
My simple code:
```
		JSON_Value *root_value = json_parse_file(jsonfile1);
		assert(root_value);
		json_serialize_to_file(root_value, jsonfile2);
		JSON_Value * second_root_value = json_parse_file(jsonfile2);
		assert(second_root_value);
```
jsonfile2 is incorrect JSON file.
second_root_value NULL.

**Comment by kgabis** [comment] 2016-10-26 17:52
Could not reproduce. Are you using the most recent version of parson?

**Comment by kgabis** [comment] 2016-10-29 11:28
I'm closing this issue. I might reopen if you're able to provide a sample that verifies this issue.

**Closed by kgabis** 2016-10-29 11:28 UTC
